# Units
units:
  km: 1000
  m: 1
  cm: 0.01
  mm: 0.001
  mi: 1609.344
  yd: 0.9144
  ft: 0.3048
  in: 0.0254

# Defaults
from: km
to: km
rounding: 2
min: 1
fallback:
  to: m
  rounding: 0